In [126]:
import numpy as np

In [21]:
#1 2d array creation and indexing 
arr=np.array([[12,5,18,7],[9,21,3,15],[6,14,25,11]])
print(arr)

print(arr[1])
print(arr[2])

[[12  5 18  7]
 [ 9 21  3 15]
 [ 6 14 25 11]]
[ 9 21  3 15]
[ 6 14 25 11]


In [140]:
#2 3d array 
arr=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr[1][1][1])
print(arr[1])
arr_new=arr[1]
print (sum(arr_new))

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
(2, 2, 3)
3
110
[[ 70  80  90]
 [100 110 120]]
[170 190 210]


In [55]:
#3 arrange()+ reshape()- logic
arr=np.arange(10,70)
print(arr)
arr_new=arr.reshape(4,5,3)
print(arr_new)

print(arr_new[2])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69]
[[[10 11 12]
  [13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]
  [37 38 39]]

 [[40 41 42]
  [43 44 45]
  [46 47 48]
  [49 50 51]
  [52 53 54]]

 [[55 56 57]
  [58 59 60]
  [61 62 63]
  [64 65 66]
  [67 68 69]]]
[[40 41 42]
 [43 44 45]
 [46 47 48]
 [49 50 51]
 [52 53 54]]


In [73]:
#4 evenly spaced array
arr=np.arange(10,100)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [91]:
#7 sorting multi diensional logic 
arr=np.array([[45,12,78,34],[23,89,11,56],[67,34,90,21]])
print(arr)


[[45 12 78 34]
 [23 89 11 56]
 [67 34 90 21]]


In [109]:
#8 flatten() vs reshape 
arr=np.arange(1,25).reshape(4,6)
print(arr)
new_arr=arr.flatten()
print(new_arr)
print(new_arr.reshape(3,8))

even_arr=(arr%2==0)
print(even_arr)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


In [123]:
#9 concatenation
arr_a=np.array([[1,2,3],[4,5,6]])
arr_b=np.array([[7,8,9],[10,11,12]])
print(arr_a)
print(arr_b)

print(arr_a+arr_b)
new_arr=(arr_a+arr_b)
print(sum(new_arr))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[22 26 30]


In [138]:
#13 
arr=np.array([[10,45,32],[67,23,89],[54,76,12]])
print(arr)
#max
for i in arr:
    if i >0:
        print i
    else:
        print 

[[10 45 32]
 [67 23 89]
 [54 76 12]]


In [144]:
arr=np.array([[10,45,32],[67,23,89],[54,76,12]])
print(arr)
print (arr.series())

[[10 45 32]
 [67 23 89]
 [54 76 12]]


AttributeError: 'numpy.ndarray' object has no attribute 'series'