In [ ]:
#numpy is a python package or a library for scientific computing , numeric computation and mainly used in 
#data science and machiene learning 

#numpy introduce a powerful data structure called The ndarray (n-dimentional array )

#ARRAY- array is a collection of hetrogenous elements denoted by square bracket[] with space sperated values 
#array allowes you to store and manipulate massive dataset with a incredible speed 

In [1]:
%timeit [j**4 for j in range (1,10000)]

1.88 ms ± 23 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [2]:
import numpy as np

In [3]:
%timeit np.arange(1,10000)**4

50.9 μs ± 990 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
#create array with numpy array() function
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5
int64


In [5]:
l=[10,20,30,40,50.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10.  20.  30.  40.  50.5]
<class 'numpy.ndarray'>
1
(5,)
5
float64


In [6]:
l=[10,20,30,'40',50.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

['10' '20' '30' '40' '50.5']
<class 'numpy.ndarray'>
1
(5,)
5
<U32


In [ ]:
#it gives first priority to string then float then integer

In [7]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
2
(2, 4)
8
int64


In [8]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)
12
int64


In [9]:
arr=np.array([[[10,20,30,40]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[10 20 30 40]]]
<class 'numpy.ndarray'>
3
(1, 1, 4)
4
int64
