In [1]:
import numpy as np

In [3]:
#direct iteration 
arr=np.arange(10,15)
print(arr)
for i in arr:
    print(i)

[10 11 12 13 14]
10
11
12
13
14


In [5]:
#indirect iteration 
arr=np.arange(10,15)
print(arr)
for i in range(len(arr)):
    print(i,arr[i])

[10 11 12 13 14]
0 10
1 11
2 12
3 13
4 14


In [6]:
arr=np.arange(10,15)
print(arr)
print(len(arr))
count=0
for i in arr:
    count=count+1
print(count)

[10 11 12 13 14]
5
5


In [7]:
arr=np.arange(10,19).reshape(3,3)
print(arr)
print()
for i in arr:
    for j in i:
        print(j)

[[10 11 12]
 [13 14 15]
 [16 17 18]]

10
11
12
13
14
15
16
17
18


In [9]:
arr=np.arange(10,22).reshape(2,2,3)
print(arr)
print()
for i in arr:
    for j in i:
        for k in j:
            print(k)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]

10
11
12
13
14
15
16
17
18
19
20
21


In [10]:
#np.nditer (arrayobject)
arr=np.arange(10,22).reshape(2,2,3)
print(arr)
for i in np.nditer(arr):
    print(i)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]
10
11
12
13
14
15
16
17
18
19
20
21


In [11]:
#np.nenumerate(arrayobject)- return inndex and value 
arr=np.arange(10,22).reshape(2,2,3)
print(arr)
for index,value in np.ndenumerate(arr):
    print(index,value)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]
(0, 0, 0) 10
(0, 0, 1) 11
(0, 0, 2) 12
(0, 1, 0) 13
(0, 1, 1) 14
(0, 1, 2) 15
(1, 0, 0) 16
(1, 0, 1) 17
(1, 0, 2) 18
(1, 1, 0) 19
(1, 1, 1) 20
(1, 1, 2) 21


In [ ]:
#question create one 1 dimension array having 5 elements (float) . take input at runtime . using array function
l=[]
for i in range(5):
    n=float(input("enter any number"))
    l.append(n)
arr=np.array(l)
print(arr)

In [3]:
import numpy as np