In [1]:
import numpy as np

In [2]:
# arrayobject.flatten() - convert multi-dimensional array into a 1D array
# it create copy of an original array.
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
arr_new=arr.flatten()
print(arr_new)
arr_new[0]=100
print(arr_new)
print(arr)

[[10 20 30 40]
 [50 60 70 80]]
[10 20 30 40 50 60 70 80]
[100  20  30  40  50  60  70  80]
[[10 20 30 40]
 [50 60 70 80]]


In [3]:
# np.insert(array,index,element)
arr=np.array([10,20,30,40,50])
print(arr)
arr1=np.insert(arr,2,100)
print(arr1)

[10 20 30 40 50]
[ 10  20 100  30  40  50]


In [4]:
arr=np.array([10,20,30,40,50])
print(arr)
arr1=np.insert(arr,2,[100,200,300])
print(arr1)

[10 20 30 40 50]
[ 10  20 100 200 300  30  40  50]


In [5]:
arr=np.array([[100,200,300],[400,500,600]])
print(arr)
print("-----****----")
arr_0=np.insert(arr,1,[10,20,30],axis=0)
print(arr_0)
print("-----****----")
arr_1=np.insert(arr,1,[10,20],axis=1)
print(arr_1)

[[100 200 300]
 [400 500 600]]
-----****----
[[100 200 300]
 [ 10  20  30]
 [400 500 600]]
-----****----
[[100  10 200 300]
 [400  20 500 600]]


In [6]:
# np.delete(array,index)
arr=np.array([100,200,300,400,500])
print(arr)
arr_new=np.delete(arr,2)
print(arr_new)
arr_new1=np.delete(arr,[2,3])
print(arr_new1)

[100 200 300 400 500]
[100 200 400 500]
[100 200 500]


In [7]:
arr=np.array([[100,200,300,400],[50,60,70,80]])
print(arr)
arr_new=np.delete(arr,1,axis=0)
print(arr_new)
arr_new1=np.delete(arr,2,axis=1)
print(arr_new1)

[[100 200 300 400]
 [ 50  60  70  80]]
[[100 200 300 400]]
[[100 200 400]
 [ 50  60  80]]


In [8]:
arr=np.array([10,11,12,13,14,15,16,17])
result=arr[arr%2==0]
print(result)

[10 12 14 16]


In [9]:
arr=np.array([10,11,12,13,14,15,16,17])
result=arr[arr>13]
print(result)

[14 15 16 17]


In [10]:
arr=np.array([10,11,12,13,14,15,16,17])
result=arr[(arr>13) & (arr<16)]
print(result)

[14 15]
