In [ ]:
#numpy is a python package or a library for scientific computing , numeric computation and mainly used in 
#data science and machiene learning 

#numpy introduce a powerful data structure called The ndarray (n-dimentional array )

#ARRAY- array is a collection of hetrogenous elements denoted by square bracket[] with space sperated values 
#array allowes you to store and manipulate massive dataset with a incredible speed 

In [1]:
%timeit [j**4 for j in range (1,10000)]

1.88 ms ± 23 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [2]:
import numpy as np

In [3]:
%timeit np.arange(1,10000)**4

50.9 μs ± 990 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
#create array with numpy array() function
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5
int64


In [5]:
l=[10,20,30,40,50.5]
arr=np.array(l)
print(arr) 
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10.  20.  30.  40.  50.5]
<class 'numpy.ndarray'>
1
(5,)
5
float64


In [6]:
l=[10,20,30,'40',50.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

['10' '20' '30' '40' '50.5']
<class 'numpy.ndarray'>
1
(5,)
5
<U32


In [ ]:
#it gives first priority to string then float then integer

In [7]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
2
(2, 4)
8
int64


In [8]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)
12
int64


In [9]:
arr=np.array([[[10,20,30,40]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[10 20 30 40]]]
<class 'numpy.ndarray'>
3
(1, 1, 4)
4
int64


In [12]:
!git push origin main 

To https://github.com/dishagagnamwar/learning-python.git
   8f43810..c02e1b1  main -> main


In [1]:
import numpy as np

In [2]:
#np.arange([start],stop,[step])
#it always return a one dimension array 
arr=np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
arr=np.arange(12)
print(arr)
arr1=arr.reshape(3,4)
print(arr1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
2


In [4]:
arr=np.arange(12)
print(arr)
arr1=arr.reshape(4,3)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [6]:
#index - position of an element in a given array 
#indexing - technique for accessing single element from a given array 
arr=np.arange(10,16)
print(arr)
print(arr[0])
print(arr[-1])

[10 11 12 13 14 15]
10
15


In [7]:
arr=np.arange(10,20).reshape(2,5)
print(arr)
print()
print(arr[0])
print(arr[0][-1])
print(arr[1][2])

[[10 11 12 13 14]
 [15 16 17 18 19]]

[10 11 12 13 14]
14
17


In [9]:
arr=np.arange(1,13).reshape(2,2,3)
print(arr)
print()
print(arr[-1])
print()
print(arr[1][0])
print(arr[1][0][1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[ 7  8  9]
 [10 11 12]]

[7 8 9]
8


In [13]:
#create a two dimension array having 8 elements using array function 
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2
(2, 4)
8
int64


In [15]:
#create three dimension array using array function having 36 elements 
arr=np.arange(1,37).reshape(3,3,4)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
<class 'numpy.ndarray'>
3
(3, 3, 4)
36
int64


In [3]:
!git push origin main

To https://github.com/dishagagnamwar/learning-python.git
   c02e1b1..8386048  main -> main
