In [24]:
import numpy as np

In [ ]:
#operators

#ADD
#np.add(arr1,arr2)
#arr1+arr2

#SUBTRACT
#np.subtract(arr1,arr2)
#arr1-arr2

#MULTIPLY
#np.multiply(arr1,arr2)
#arr1*arr2

#DIVIDE
#np.divide(arr1,arr2)
#arr1/arr2

#POWER
#np.power(arr1,arr2)
#arr1**arr2

#RECIPROCAL
#np.reciprocal(arr1)
#1/arr1

#mod
#np.mod(arr1,arr2)
#arr%arr2


In [10]:
#arithmetic operators

#addition
arr=np.array([10,2030,40])
print(arr)
arr_new=arr+4
print(arr_new)

[  10 2030   40]
[  14 2034   44]


In [12]:
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
print(arr1)
print(arr2)
arr_new=arr1+arr2
print(arr_new)

arr_new1=np.add(arr1,arr2)
print(arr_new1)

[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[11 22 33 44]


In [17]:
#addition in 2 dimension
arr1=np.array([[10,20,30,40],[45,86,54,53]])
arr2=np.array([[1,2,3,4],[1,8,65,8]])
print(arr1)
print(arr2)
arr_new=arr1+arr2
print(arr_new)

arr_new1=np.add(arr1,arr2)
print(arr_new1)

[[10 20 30 40]
 [45 86 54 53]]
[[ 1  2  3  4]
 [ 1  8 65  8]]
[[ 11  22  33  44]
 [ 46  94 119  61]]
[[ 11  22  33  44]
 [ 46  94 119  61]]


In [18]:
#addition in 3 dimension
arr1=np.array([[[10,20,30,40],[45,86,54,53]],[[23,44,5,3],[98,21,4,56]]])
arr2=np.array([[[1,2,3,4],[1,8,65,8]],[[10,20,30,40],[45,86,54,53]]])
print(arr1)
print(arr2)
arr_new=arr1+arr2
print(arr_new)

arr_new1=np.add(arr1,arr2)
print(arr_new1)

[[[10 20 30 40]
  [45 86 54 53]]

 [[23 44  5  3]
  [98 21  4 56]]]
[[[ 1  2  3  4]
  [ 1  8 65  8]]

 [[10 20 30 40]
  [45 86 54 53]]]
[[[ 11  22  33  44]
  [ 46  94 119  61]]

 [[ 33  64  35  43]
  [143 107  58 109]]]
[[[ 11  22  33  44]
  [ 46  94 119  61]]

 [[ 33  64  35  43]
  [143 107  58 109]]]


In [20]:
#substract
arr1=np.array([10,20,30,40])
arr2=np.array([1,2,3,4])
print(arr1)
print(arr2)
arr_new=arr1-arr2
print(arr_new)

arr_new1=np.subtract(arr1,arr2)
print(arr_new1)

[10 20 30 40]
[1 2 3 4]
[ 9 18 27 36]
[ 9 18 27 36]


In [13]:
#reciprocal
arr=np.array([10,20,30,40])
print(arr)
arr_new=1/arr
print(arr_new)

arr_new1=np.reciprocal(arr)
print(arr_new1)

[10 20 30 40]
[0.1        0.05       0.03333333 0.025     ]
[0 0 0 0]


In [14]:
#multiply 
arr=np.array([20,30,40,50])
print(arr)
arr_new=arr*5
print(arr_new)

[20 30 40 50]
[100 150 200 250]


In [15]:
#multiply
arr1=np.array([10,60,30,80])
arr2=np.array([1,2,3,4])
print(arr1)
print(arr2)
arr_new=arr1*arr2
print(arr_new)

arr_new1=np.multiply(arr1,arr2)
print(arr_new1)

[10 60 30 80]
[1 2 3 4]
[ 10 120  90 320]
[ 10 120  90 320]


In [16]:
#divide and reciprocal
arr1=np.array([50,60,45,36])
arr2=np.array([2,6,4,5])
print(arr1)
print(arr2)

arr_new=arr1/arr2
print(arr_new)

arr_new1=np.reciprocal(arr)
print(arr_new1)

[50 60 45 36]
[2 6 4 5]
[25.   10.   11.25  7.2 ]
[0 0 0 0]


In [5]:
#max()
arr=np.array([100,14,67,128,97])
print(arr)
print(np.max(arr))
max_value=arr[0]
for i in arr:
    if i >max_value:
        max_value=i
print(max_value)

[100  14  67 128  97]
128
128


In [7]:
arr1=np.array([[110,23,44,56],[12,34,556,67]])
print(arr1)
print(np.max(arr1))
print(np.max(arr1,axis=0))
print(np.max(arr1,axis=1))

[[110  23  44  56]
 [ 12  34 556  67]]
556
[110  34 556  67]
[110 556]


In [8]:
arr=np.array([[[10,2,34],[64,31,5]],[[68,22,36],[110,7,15]]])
print(arr)
print(np.max(arr))
print(np.max(arr,axis=0))
print(np.max(arr,axis=1))
print(np.max(arr,axis=2))

[[[ 10   2  34]
  [ 64  31   5]]

 [[ 68  22  36]
  [110   7  15]]]
110
[[ 68  22  36]
 [110  31  15]]
[[ 64  31  34]
 [110  22  36]]
[[ 34  64]
 [ 68 110]]


In [21]:
#min
arr=np.array([100,14,67,128,97])

min_value=arr[0]
for i in arr:
    if i <min_value:
        min_value=i
print(min_value)

14


In [25]:
arr=np.array([100,76,12,56,87,123,89])
print(arr)
print(np.max(arr),np.argmax(arr))
print(np.min(arr),np.argmin(arr))

[100  76  12  56  87 123  89]
123 5
12 2


In [26]:
arr=np.array([[100,23,45,65],[78,46,67,34]])
print(arr)
print(np.max(arr),np.argmax(arr))
print(np.min(arr),np.argmin(arr))

[[100  23  45  65]
 [ 78  46  67  34]]
100 0
23 1


In [30]:
arr=np.array([[100,23,45,65],[78,46,67,34]])
print(arr)
print(np.argmax(arr,axis=0))
print(np.argmin(arr,axis=0))

[[100  23  45  65]
 [ 78  46  67  34]]
[0 1 1 0]
[1 0 0 1]


In [31]:
arr=np.array([900,10000,25,36,100])
print(arr)
print(np.sqrt(arr))

[  900 10000    25    36   100]
[ 30. 100.   5.   6.  10.]


In [35]:
arr=np.array([[900,10000,25,100],[81,4900,3600,400]])
print(arr)
print(np.sqrt(arr))

[[  900 10000    25   100]
 [   81  4900  3600   400]]
[[ 30. 100.   5.  10.]
 [  9.  70.  60.  20.]]


In [38]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.cumsum(arr))

[10 20 30 40 50]
[ 10  30  60 100 150]


In [41]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(np.cumsum(arr))

[[10 20 30 40]
 [50 60 70 80]]
[ 10  30  60 100 150 210 280 360]


In [44]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(np.cumsum(arr,axis=0))
print(np.cumsum(arr,axis=1))

[[10 20 30 40]
 [50 60 70 80]]
[[ 10  20  30  40]
 [ 60  80 100 120]]
[[ 10  30  60 100]
 [ 50 110 180 260]]


In [45]:
#BROADCASTING 
arr1=np.array([1,2,3,4])
arr2=np.array([4])
print(arr1+arr2)

[5 6 7 8]


In [47]:
arr1=np.array([10,20,30])
arr2=np.array([[100],[200],[300]])
print(arr1+arr2)

[[110 120 130]
 [210 220 230]
 [310 320 330]]


In [48]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,7,8])
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 