In [2]:
import numpy as np

In [3]:
# stack
arr1=np.array([10,20,30,40])
arr2=np.array([100,200,300,400])
print(arr1)
print(arr2)
print("----******-----")
arr_new=np.stack((arr1,arr2))
print(arr_new)
print("----******-----")
arr_new=np.stack((arr1,arr2),axis=0)
print(arr_new)
print("----******-----")
arr_new=np.stack((arr1,arr2),axis=1)
print(arr_new)

[10 20 30 40]
[100 200 300 400]
----******-----
[[ 10  20  30  40]
 [100 200 300 400]]
----******-----
[[ 10  20  30  40]
 [100 200 300 400]]
----******-----
[[ 10 100]
 [ 20 200]
 [ 30 300]
 [ 40 400]]


In [4]:
# TRANSPOSE - arrayobj.T
arr=np.array([[100,200,300,400]])
print(arr)
print(arr.shape)
arr_1=arr.T
print(arr_1)
print(arr_1.shape)

[[100 200 300 400]]
(1, 4)
[[100]
 [200]
 [300]
 [400]]
(4, 1)


In [5]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[10,11,12,13],[14,15,16,17]])
print(arr1)
print(arr2)
print("-----****------")
arr_new=np.stack((arr1,arr2))
print(arr_new)
print("-----****------")
arr_new=np.stack((arr1,arr2),axis=0)
print(arr_new)
print("-----****------")
arr_new=np.stack((arr1,arr2),axis=1)
print(arr_new)
print("-----****------")
arr_new=np.stack((arr1,arr2),axis=2)
print(arr_new)

[[1 2 3 4]
 [5 6 7 8]]
[[10 11 12 13]
 [14 15 16 17]]
-----****------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 11 12 13]
  [14 15 16 17]]]
-----****------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 11 12 13]
  [14 15 16 17]]]
-----****------
[[[ 1  2  3  4]
  [10 11 12 13]]

 [[ 5  6  7  8]
  [14 15 16 17]]]
-----****------
[[[ 1 10]
  [ 2 11]
  [ 3 12]
  [ 4 13]]

 [[ 5 14]
  [ 6 15]
  [ 7 16]
  [ 8 17]]]


In [6]:
# split
# np.split(arrobj,no of array)
# split works on an equal size array.
arr=np.arange(1,9)
print(arr)
l=np.split(arr,4)
for i in l:
    print(i)

[1 2 3 4 5 6 7 8]
[1 2]
[3 4]
[5 6]
[7 8]


In [7]:
arr=np.arange(1,9)
print(arr)
print(np.split(arr,3))

[1 2 3 4 5 6 7 8]


ValueError: array split does not result in an equal division

In [8]:
arr=np.arange(1,9)
print(arr)
print(np.array_split(arr,2))

[1 2 3 4 5 6 7 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [9]:
arr=np.arange(1,9)
print(arr)
print(np.array_split(arr,3))

[1 2 3 4 5 6 7 8]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [10]:
arr=np.arange(1,10)
print(arr)
print(np.array_split(arr,2))

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]


In [11]:
# where
arr=np.array([10,3,4,5,18,8,9,11,56])
print(arr)
print(np.where(arr%2==0))
print(np.where(arr>5))

[10  3  4  5 18  8  9 11 56]
(array([0, 2, 4, 5, 8]),)
(array([0, 4, 5, 6, 7, 8]),)


In [12]:
# np.sort(array)
arr=np.sort([100,23,45,21,46,57,12])
arr_new=np.sort(arr)
print(arr_new)

[ 12  21  23  45  46  57 100]


In [13]:
arr=np.sort([100,23,45,21,46,57,12])
arr_new=np.sort(arr)[::-1]
print(arr_new)

[100  57  46  45  23  21  12]


In [14]:
!git add .

In [15]:
!git commit -m "numpy "

[main 170e6ab] numpy
 4 files changed, 404 insertions(+), 3 deletions(-)
 rename NUMPY/.ipynb_checkpoints/{Untitled1-checkpoint.ipynb => numpy stack ,transpose etc-checkpoint.ipynb} (100%)
 rename NUMPY/{Untitled1.ipynb => numpy stack ,transpose etc.ipynb} (100%)


In [16]:
!git push origin main

To https://github.com/dishagagnamwar/learning-python.git
   8c50470..170e6ab  main -> main
