In [1]:
import numpy as np

In [2]:
#linspace(start,stop,[number=50... by default],endpoint=True)
#return evenly spaced array 
arr=np.linspace(0,20,5)
print(arr)

[ 0.  5. 10. 15. 20.]


In [4]:
arr=np.linspace(0,20)
print(len(arr))

50


In [5]:
arr=np.linspace(0,20,5,endpoint=False)
print(arr)

[ 0.  4.  8. 12. 16.]


In [6]:
#zeros()- zero filled array 
arr=np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [9]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#ones()- return ones filled array 
arr=np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [11]:
arr=np.ones((2,3,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [1]:
!git add .

In [2]:
!git commit -m"ones and zeros inn array "

[main 5097406] ones and zeros inn array
 2 files changed, 333 insertions(+), 22 deletions(-)


In [3]:
!git push origin main 

To https://github.com/dishagagnamwar/learning-python.git
   3c7e942..5097406  main -> main
