In [2]:
import numpy as np

In [4]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([2,2,2])
print(arr1)
print(arr2)

print(arr1+arr2)

[[1 2 3]
 [4 5 6]]
[2 2 2]
[[3 4 5]
 [6 7 8]]


In [5]:
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([2,2,2])
print(arr1)
print(arr2)

print(arr1+arr2)

[[1 2]
 [3 4]
 [5 6]]
[2 2 2]


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [6]:
# join two array
# concatenate - always return same dimension array with different 
# shape(increase shape)
# dimension and shape both are same
arr1=np.array([10,20,30,40])
arr2=np.array([100,200,300,400])
print(arr1)
print(arr2)

[10 20 30 40]
[100 200 300 400]


In [7]:
arr_new=np.concatenate((arr1,arr2))
print(arr_new)

[ 10  20  30  40 100 200 300 400]


In [8]:
# dimension same but shape are different.
arr1=np.array([10,20,30,40])
arr2=np.array([100,200,300,400,500,600])
print(arr1)
print(arr2)

[10 20 30 40]
[100 200 300 400 500 600]


In [9]:
arr_new=np.concatenate((arr1,arr2))
print(arr_new)

[ 10  20  30  40 100 200 300 400 500 600]


In [11]:
# different dimension - throw error for concatenate function - arrays  must be same dimension.
arr1=np.array([10,20,30,40])
arr2=np.array([[100,200,300,400]])
print(arr1)
print(arr2)

arr_new=np.concatenate((arr1,arr2))
print(arr_new)

[10 20 30 40]
[[100 200 300 400]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [12]:
# 2 dimension - dimension and shape are same
arr1=np.array([[100,200,300],[400,500,600]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)

[[100 200 300]
 [400 500 600]]
[[1 2 3]
 [4 5 6]]


In [13]:
# by default axis - 0 i.e rows
arr_new=np.concatenate((arr1,arr2))
print(arr_new)

[[100 200 300]
 [400 500 600]
 [  1   2   3]
 [  4   5   6]]


In [14]:
arr_new=np.concatenate((arr1,arr2),axis=1)
print(arr_new)

[[100 200 300   1   2   3]
 [400 500 600   4   5   6]]


In [15]:
# dimension same shape different
arr1=np.array([[100,200],[300,400],[500,600]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)
arr_new=np.concatenate((arr1,arr2),axis=1)
print(arr_new)

[[100 200]
 [300 400]
 [500 600]]
[[1 2 3]
 [4 5 6]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [16]:
arr1=np.array([[100,200,300,400],[300,400,500,600]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)
arr_new=np.concatenate((arr1,arr2),axis=1)
print(arr_new)

[[100 200 300 400]
 [300 400 500 600]]
[[1 2 3]
 [4 5 6]]
[[100 200 300 400   1   2   3]
 [300 400 500 600   4   5   6]]
