In [2]:
import numpy as np

In [2]:
arr=np.random.rand(5)
print(arr)

[0.07814893 0.65508893 0.95680073 0.20906515 0.94249596]


In [4]:
arr=np.random.rand(2,4)
print(arr)

[[0.62360948 0.46187991 0.57155881 0.06791798]
 [0.24676533 0.40671152 0.93569301 0.74080334]]


In [6]:
arr=np.random.randn(5)
print(arr)
print(arr.mean())

[-0.33083106 -0.78297583  0.59736385  2.4835334  -0.99004333]
0.19540940758859207
